cache:
  - packages -> **\packages.config
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

install:
  - choco install gitversion.portable -y

nuget:
  project_feed: true

configuration: Release

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateassemblyinfo CommonAssemblyInfo.cs /b (get-item env:APPVEYOR_REPO_BRANCH).Value

after_build:
  - nuget pack sources/ConfigurationManager/ConfigurationManager.csproj
  - nuget pack sources/Octopus/Octopus.csproj

artifacts:
  - path: '*.nupkg'
